version: "3.9"

networks:
  microapp_net:

volumes:
  mongo_volume:
    name: mongo_vol

services:
  mongo:
    image: mongo:latest
    container_name: mongo-products
    environment:
      - MONGO_INITDB_DATABASE=products
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_volume:/data/db
      - mongo_volume:/data/configdb
    ports:
      - '27017-27019:27017-27019'
    networks:
      - microapp_net

  microapp-products:
    build: .
    container_name: microapp-products
    environment:
      - spring_data_mongodb_host=mongo
    ports:
      - "8081:8080"
    networks:
      - microapp_net
    depends_on:
      - mongo