version: "3.9"

networks:
  microapp_net:

volumes:
  postgres_volume:
    name: postgres_vol

services:
  postgres:
    image: postgres:latest
    container_name: postgres-orders
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ordersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - microapp_net

  microapp-orders:
    build: .
    container_name: microapp-orders
    environment:
      - spring_datasource_url=jdbc:postgresql://postgres:5432/ordersdb
    ports:
      - "8081:8080"
    networks:
      - microapp_net
    depends_on:
      - postgres